"""Reproducible synthetic analytical examples. No client or production data.
Requires numpy, scipy, scikit-learn. Run only when changing the sample dataset.
"""
from pathlib import Path
import json
import numpy as np
import sklearn
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.inspection import permutation_importance
from sklearn.metrics import average_precision_score

ROOT=Path(__file__).resolve().parents[1]
rng=np.random.default_rng(20260907)
X,y=make_classification(n_samples=4000,n_features=10,n_informative=6,n_redundant=2,weights=[.9,.1],class_sep=1.05,flip_y=.015,random_state=42)
Xtr,Xte,ytr,yte=train_test_split(X,y,test_size=.25,stratify=y,random_state=42)
models=[HistGradientBoostingClassifier(max_iter=120,max_leaf_nodes=15,l2_regularization=2,random_state=42),RandomForestClassifier(n_estimators=160,min_samples_leaf=4,max_depth=10,random_state=42,n_jobs=2),make_pipeline(StandardScaler(),LogisticRegression(max_iter=500,random_state=42))]
model_data=[]
for name,model in zip(['Gradient Boosting','Random Forest','Logistic Regression'],models):
 model.fit(Xtr,ytr);scores=model.predict_proba(Xte)[:,1]
 imp=permutation_importance(model,Xte,yte,n_repeats=5,scoring='average_precision',random_state=42,n_jobs=2)
 model_data.append({'name':name,'scores':np.round(scores,7).tolist(),'ap':float(average_precision_score(yte,scores)),'importance':np.round(imp.importances_mean,5).tolist()})
 print(name,round(model_data[-1]['ap'],3),flush=True)
# Unit-level panel, 80 units x 12 months. Treatment assignment is synthetic.
units=[]
for i in range(80):
 treated=i%2;segment=(i//2)%2;base=rng.normal(101,7);individual=rng.normal(0,2)
 vals=[]
 for m in range(12):
  season=[0,1.5,-.6,1.8,.2,1.1,-.8,.5,1.7,.4,2.1,.8][m]
  treatment=treated*max(0,m-5)*(1.35+segment*.35+individual*.05)
  vals.append(round(base+.65*m+season+treatment+rng.normal(0,3.2),2))
 units.append({'id':i+1,'treated':treated,'segment':segment,'values':vals})
# Daily observations with explicit nulls and repeated record IDs.
rows=[]
for i in range(2400):
 region=int(rng.integers(0,4));month=int(rng.integers(1,13))
 value=round(float(rng.lognormal(4.1+region*.12+np.sin(month/12*np.pi*2)*.17,.42)),1)
 if rng.random()<.02:value=round(value*3.5,1)
 if rng.random()<.035:value=None
 rows.append([i+1,region,month,value])
rows.extend([rows[int(i)].copy() for i in rng.choice(2400,24,replace=False)])
# Request traces: all aggregates in the browser derive from these records.
traces=[]
for i in range(420):
 minute=60-i/7;route=i%3;error=(i%61==0 or i%79==0)
 retrieval=int(rng.uniform(65,230));rerank=int(rng.uniform(25,120));first=int(rng.uniform(160,550));generation=int(rng.lognormal(6.5,.45))
 if 21<minute<28: first+=550
 duration=5000 if error else retrieval+rerank+first+generation
 traces.append({'id':f'tr_{420-i:04d}','minute':round(minute,3),'route':route,'parts':[retrieval,rerank,first,generation],'duration':duration,'tokens':0 if error else int(rng.integers(380,2200)),'error':error})
payload={'meta':{'seed':20260907,'sklearn':sklearn.__version__,'modelTrain':len(ytr),'modelTest':len(yte),'features':10},'models':{'labels':yte.tolist(),'items':model_data},'policy':units,'observations':rows,'traces':traces}
(ROOT/'assets/js/analysis-samples.mjs').write_text('// Generated by scripts/generate-analysis-data.py. Synthetic data only.\nexport default '+json.dumps(payload,separators=(',',':'))+';\n')
print('Wrote synthetic observations, fitted model scores, panel and request traces.')
